### ISSUE TITLE
WdslProvider Accept both https and http for single type

### ISSUE THREAD

**Issue by jon49** [fsprojects/FSharp.Data.TypeProviders#11]
### Description

I have a service that uses https when in production mode, but uses http for dev and beta mode.

This is basically the error:

> The provided URI scheme 'https' is invalid; expected 'http'

I can dynamically change the endpoint address. But there doesn't appear to be a way to change the transportMode.

As seen here:
https://github.com/fsharp/fsharp/blob/master/src/fsharp/FSharp.Data.TypeProviders/TypeProviders.fs#L984
### Repro steps

Create a WsdlProvider for an `http` url and then change the endpoint to `https` later on in the code. You can do the opposite also. Both will give errors.

``` fsharp
type ExampleService = WsdlService<"http://example.com/service.svc">
let exampleService () =
        ExampleService.GetBasicHttpBinding_IExampleService (System.ServiceModel.EndpointAddress "https://production.example.com/service.svc"
```
### Expected behavior

The expected behavior is to be able to switch between `http` and `https` at runtime. I don't know if it is possible though.
### Actual behavior

When switching between `https` and `http` the error is given:

> The provided URI scheme 'https' is invalid; expected 'http'
### Known workarounds

What is done is C# is to use the Web.config file. When compiling use Web.Release.config for production.
### Related information
- Windows 7
- .NET Runtime

**Comment by denmerc** [comment]
I have a similar issue. A partner of ours has recently changed their api to use https. I have no need to change at runtime but is it possible to use https with WSDLService Type Provider? If so, how so?

**Comment by dsyme** [comment]
Perhaps take a look through the implementation, there may be a simple fix?

**Comment by gfritz** [comment]
The default binding uses HTTP (GetBasic**Http**Binding_IExampleService), so you have to use a CustomBinding with an HttpsTransportBindingElement.

This worked for my team in the same scenario you described:

```F#
open System.ServiceModel
open System.ServiceModel.Channels

let private getTransportBinding (uri : Uri) =
    // handle other schemes if you want
    match uri.Scheme = "https" with
    | true -> HttpsTransportBindingElement() :> TransportBindingElement
    | false -> HttpTransportBindingElement() :> TransportBindingElement

// pull from config or whatever
let runtimeServiceUrl = Uri("https://production.example.com/service.svc")
let transport = getTransportBinding(runtimeServiceUrl)
let binding = CustomBinding(transport)
let address = EndpointAddress(runtimeServiceUrl)
let client = ExampleService.ServiceTypes.IExampleServiceSoapClient(binding, address)
```

ExampleService can still be HTTP at compile time this way.

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/

For WSDL see https://github.com/fsprojects/FSharp.Data.WsdlProvider for a more recent provider, also https://github.com/fsprojects/SwaggerProvider
