### ISSUE TITLE
WSDLService returning first entry in array response

### ISSUE THREAD

**Issue by rkosafo** [fsprojects/FSharp.Data.TypeProviders#14]
### Description

I'm using the WSDLService type provider to access a webservice. All calls have worked so far with the exception of two call. One of issues is as detailed below. Is there a known workaround?
### Repro steps

Given the `xml` below (part of the `wsdl`) , 

```
<xs:complexType name="tQryUserReq">
    <xs:sequence>
        <xs:element name="MSISDN">
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:maxLength value="60"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:element>
    </xs:sequence>
</xs:complexType>
<xs:element name="QryUserReq" type="ns:tQryUserReq"/>
<xs:complexType name="tQryUserResp">
    <xs:sequence>
        <xs:element name="PricePlanGoupDtoList" nillable="true" type="ns:tPricePlanGroupDto2"/>
    </xs:sequence>
</xs:complexType>
<xs:element name="QryUserResp" type="ns:tQryUserResp"/>
```

The signature of the generated function is

```
QryUser(AuthHeader:tAuthHeader, QryUserReq:tQryUserReq)
  : tPricePlanGroupDto2
```

Usage

```
let ret = client.QryUser(getQueryAuthHeader(),req)
    //ret is of type tPricePlanGroupDto2
```
### Expected behavior

An array of data. It actually has two objects.
Was expecting the return type to be `tQryUserResp` but got `tPricePlanGroupDto2`
### Actual behavior

A response with a single object not the expected array. No error though.
### Related information
- Operating system : Windows 10
- Branch: FSharp.Data.TypeProviders v 5.0.0.2 from nuget
- .NET Runtime, CoreCLR or Mono Version: 4.6.1
- Performance information, links to performance testing scripts

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/

For WSDL see https://github.com/fsprojects/FSharp.Data.WsdlProvider for a more recent provider, also https://github.com/fsprojects/SwaggerProvider
