### ISSUE TITLE
How to manually manage transaction/isolation level?

### ISSUE THREAD

**Issue by jcmincke** [fsprojects/FSharp.Data.TypeProviders#15]
I cannot find a way to manually begin/commit/rollback a transaction or to explicitly set its isolation level.

SubmitUpdates() seems to automatically create its own transaction (if any?).

Is that behavior wanted/expected or am I missing something?

**Comment by dsyme** [comment]
How about the techniqu here? http://stackoverflow.com/questions/867643/how-to-use-transactions-with-a-datacontext?

**Comment by jcmincke** [comment]
It does not really help. Here is my code:

```

type sql =
  SqlDataProvider<
  dbVendor,
  connString,
  "",         //ConnectionNameString can be left empty 
  resPath,
  indivAmount,
  useOptTypes>

let createPerson fn n =
    let db = sql.GetDataContext()
    let opt = new TransactionOptions ()
    //opt.IsolationLevel <-IsolationLevel.ReadCommitted  // BTW this assignement does not compile (!?)
    use ts = new TransactionScope(TransactionScopeOption.Required, opt,
                           EnterpriseServicesInteropOption.Automatic)
    let p = db.Public.Person.Create(fn, n)
    db.SubmitUpdates()
    ts.Dispose()
```

On Windows: 
I get [this exception when submitting changes](https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=FR-FR&k=k%28EHRTargetInvocation%29&rd=true).
On Mono:
No exception but no rollback.

**Comment by dsyme** [comment]
@jcmincke Can you please check the InnerException of the TargetInvocationException?

**Comment by jcmincke** [comment]
@dsyme 
The exception System.Reflection.TargetInvocationException was not handled/caught.
Message: An non-handled exception 'System.Reflection.TargetInvocationException' occurred in mscorlib.dll
Additional Information : Exception has been thrown by the target of an invocation.

Original message in french
L'exception System.Reflection.TargetInvocationException n'a pas été gérée
Message: Une exception non gérée du type 'System.Reflection.TargetInvocationException' s'est produite dans mscorlib.dll
Informations supplémentaires : Exception has been thrown by the target of an invocation.

BTW, removing 'EnterpriseServicesInteropOption.Automatic' seems to solve the problem.

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/

For WSDL see https://github.com/fsprojects/FSharp.Data.WsdlProvider for a more recent provider, also https://github.com/fsprojects/SwaggerProvider
