### ISSUE TITLE
Compatibility with azure functions

### ISSUE THREAD

**Issue by davidtme** [fsprojects/FSharp.Data.TypeProviders#17]
### Description

I’ve taken the sample from http://fsprojects.github.io/FSharp.Data.TypeProviders/wsdl.html and tried to get it to work with azure functions via the [azure-functions-cli](https://github.com/Azure/azure-functions-cli) however it’s isn’t compiling:
```
startup(2,1): warning FS3005: Referenced assembly 'C:\Users\xx\.nuget\packages\FSharp.Data.TypeProviders\5.0.0.2\lib\net40\FSharp.Data.TypeProviders.dll' has assembly level attribute 'Microsoft.FSharp.Core.CompilerServices.TypeProviderAssemblyAttribute' but no public type provider classes were found
C:\xxx\run.fsx(9,14): error FS39: The type 'WsdlService' is not defined
```

### Repro steps

__run.fsx__
```F#
open FSharp.Data.TypeProviders

type Wsdl1 = WsdlService<"http://api.microsofttranslator.com/V2/Soap.svc">

let Run(myTimer : TimerInfo, state : string, log : TraceWriter) =
    let ctxt = Wsdl1.GetBasicHttpBinding_LanguageService()
    ignore()
```

__project.json__
```JSON
{
  "frameworks": {
    "net46": {
      "dependencies": {
        "FSharp.Data.TypeProviders": "5.0.0.2"
      }
    }
  }
}
```
__function.json__
```JSON
{
  "disabled": false,
  "bindings": [
    {
      "name": "myTimer",
      "type": "timerTrigger",
      "direction": "in",
      "schedule": "0 * * * * *"
    }
  ]
}
```

* Windows
* FSharp.Data.TypeProviders v5.0.0.2
* azure-functions-cli v1.0.0-beta.92

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/

For WSDL see https://github.com/fsprojects/FSharp.Data.WsdlProvider for a more recent provider, also https://github.com/fsprojects/SwaggerProvider
