### ISSUE TITLE
The project needs a logo

### ISSUE THREAD

**Issue by sergey-tihon** [fsprojects/FSharp.Data.TypeProviders#2]
@forki @dsyme Any ideas how it may look like?

Option 1:
![logo](https://cloud.githubusercontent.com/assets/1197905/12581370/359b9a06-c447-11e5-8235-e342203060a9.png)

Option 2:
![logo2](https://cloud.githubusercontent.com/assets/1197905/12581372/398a5d5a-c447-11e5-8c69-51d8a5ad9800.png)

**Comment by forki** [comment]
question is: what do these type providers have in common? Or stated differently: do we want to keep them in one repo/package ;-)

**Comment by sergey-tihon** [comment]
They use `.NET Framework generators` :smile:

**Comment by chillitom** [comment]
How about something factory related like a hammer or a forge and a `<'T>`?  To really get across the fact that types are created dynamically (if that's the right way of putting it).

Or maybe even crazier a generator with a `<'T>` on the side.

**Comment by sergey-tihon** [comment]
Option 3:
![image](https://cloud.githubusercontent.com/assets/1197905/12582011/5795164c-c44b-11e5-9f52-568fc8047817.png)

**Comment by isaacabraham** [comment]
I like the first one. Except it's not LINQ but LinqToSQL (which in turn uses AFAIK .dbmx).

**Comment by tpetricek** [comment]
just put a big "M$" in the right bottom corner ;-)

**Comment by sergey-tihon** [comment]
Option 4:
![image](https://cloud.githubusercontent.com/assets/1197905/12582199/ad9ce564-c44c-11e5-9567-a07b04026d78.png)
Option 5:
![image](https://cloud.githubusercontent.com/assets/1197905/12582203/b4ed94a8-c44c-11e5-981d-2b625df2ced6.png)

**Comment by forki** [comment]
Option 5 needs more bling bling.

**Comment by nanostick** [comment]
- Option 1: We should adopt this approach as much as possible: Change anticipation! New technologies are becoming available all the time.
- Option 2: I didn't understand what you mean with that serpent/wave! Flow?
- Option 3: I see it as a toilet, sorry! :)

**Comment by kerams** [comment]
Make the M$ in Comic Sans while you're at it ;)

@nanostick That wave is the logo of .NET (the newer one).

**Comment by sergey-tihon** [comment]
Option 6:
![image](https://cloud.githubusercontent.com/assets/1197905/12582643/673f99c4-c44f-11e5-9c4b-30d6fa65ed5b.png)

Option 7:
![image](https://cloud.githubusercontent.com/assets/1197905/12582626/5af9b91a-c44f-11e5-8fd6-cd1506b62e96.png)

**Comment by Krzysztof-Cieslak** [comment]
Option 7 :+1:

**Comment by isaacabraham** [comment]
Could always use the Microsoft logo (the four coloured square)?

**Comment by forki** [comment]
It's all fun, but please don't use MS logo or .NET logo. There must be something else that these projects have in common. Otherwise we should really consider to split further.

**Comment by sergey-tihon** [comment]
Looks like Option 4 is the most reasonable one (at least for now)

**Comment by isaacabraham** [comment]
@sergey-tihon yes. Let's be honest, the TPs in there are a bit random - SQL ORMs, WSDL, OData etc. etc. - that's as good an icon as we're going to get I think.

**Comment by nanostick** [comment]
@kerams, @sergey-tihon Oops! Yes, it is! Just realized that I missed that. I shall never forget this moment and the .NET logo, of course! :) Thank you!

**Comment by tpetricek** [comment]
My M$ suggestion was a joke, just for the record. I was also thinking of can of worms though.

More seriously, I much prefer the simple style of logos that F# Data / F# Charting / F# Data Toolbox use (http://fsharp.github.io/FSharp.Data/).

I'm sure it's possible to come up with just a very simple shape to capture the idea! If you cannot draw it in ASCII art, it is too complex! How about:

```
  __
 /  \
/ /| \   _____
\ \| /  |_____|
 \__/ __/_   _\__
     |____| |____|
```

Looks like a UML diagram of all those code-generated classes you get in VS :)

**Comment by sergey-tihon** [comment]
Option 8:
![image](https://cloud.githubusercontent.com/assets/1197905/12587279/bec98ff0-c464-11e5-8dae-adb8b90be544.png)

Option 9:
![image](https://cloud.githubusercontent.com/assets/1197905/12587427/595500d6-c465-11e5-8bff-1a76b9fdb80d.png)

@tpetricek Like these of even simpler?)

**Comment by jackfoxy** [comment]
8 and 9 are more suggestive of data. Perhaps tweak them a little more to suggest data model diagrams. Add one-to-many and one-to-one indicators on the paths.

**Comment by sergey-tihon** [comment]
And we are pretty close to logo for [GraphProvider](https://www.nuget.org/packages/GraphProvider/) ;)

**Comment by tpetricek** [comment]
I like both 8 & 9 :)

**Comment by dsyme** [comment]
I like 8 & 9, please feel free to submit a follow-up PR for this (I accepted the one @sergey-tihon already submitted)

**Comment by dsyme** [comment]
(closing this issue but please feel free to change to 8 or 9 in  a PR)

**Comment by sergey-tihon** [comment]
Option 10: // cc @jackfoxy 
![image](https://cloud.githubusercontent.com/assets/1197905/12591449/d96e5976-c478-11e5-9cea-98559cda9caf.png)

**Comment by jackfoxy** [comment]
@sergey-tihon the top one does not make sense. Otherwise nice.
