### ISSUE TITLE
SqlDataConnection: Cannot build the type provider when exists a table named "dbo.Connection"

### ISSUE THREAD

**Issue by livioc** [fsprojects/FSharp.Data.TypeProviders#24]
### Description

When in the database exists the table dbo.Connection the compiler fails to build the type because it already has a property named Connection.
A solution can be to add the "dbo_"' prefix to the property in this special case

### Repro steps

Please provide the steps required to reproduce the problem

1. Create a database named MyDatabase with this table 
CREATE TABLE [dbo].[Connection](
	[Name] [nchar](10) NULL
)

2. Compile this code
open FSharp.Data.TypeProviders

type Sql = SqlDataConnection<"Data Source=MyServer;Initial Catalog=MyDatabase;Integrated Security=True;">

[<EntryPoint>]
let main _ = 
    //let db = Sql.GetDataContext()
    0 // return an integer exit code

### Expected behavior

the SQL type is correctly build

### Actual behavior

The build fails with the error FS2014:

A problem occurred writing the binary 'C:\Projects\Prova_F\ConsoleApplication1\obj\Debug\ConsoleApplication1.exe': Error in pass2 for type Program, error: Error in pass2 for type Sql, error: Error in pass2 for type ServiceTypes, error: Error in pass2 for type SimpleDataContextTypes, error: Error in pass2 for type MyDatabase, error: duplicate entry 'Connection' in property table	ConsoleApplication1	

### Known workarounds

Change the schema or the name of the table Connection

### Related information 
SQL Server 2014
Console Application compiled with vs 2017 and .net framework

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/

For WSDL see https://github.com/fsprojects/FSharp.Data.WsdlProvider for a more recent provider, also https://github.com/fsprojects/SwaggerProvider
