### ISSUE TITLE
Update to latest TPSDK

### ISSUE THREAD

**Issue by baronfel** [fsprojects/FSharp.Data.TypeProviders#26]
### Description
 (This is a detailed description for an interested member of the FSSF Slack, @gfritz)

In order to be a proper cross-targeting TP this repo needs to be updated to the newest SDK.
There will likely need to be other changes to allow for full xplat support (mentioned in other issues around mono tooling and whatnot), but this step will at least allow the TP to be used successfully with dotnet build on windows machines.

### Repro steps

Procedure:
0. run the build script `./build.cmd` to build the project in its current state
1. Add the TPSDK file dependencies to `paket.dependencies`:
```
github fsprojects/FSharp.TypeProviders.StarterPack src/ProvidedTypes.fsi
github fsprojects/FSharp.TypeProviders.StarterPack src/ProvidedTypes.fs
github fsprojects/FSharp.TypeProviders.StarterPack src/ProvidedTypesTesting.fs
```
2. Add the files to the `paket.references` in the `FSharp.Data.TypeProviders` project (ignore `ProvidedTypesTesting.fs` for now):
```
File: ProvidedTypes.fsi
File: ProvidedTypes.fs
```
3. Remove the old Type Provider SDK files from the `FSharp.Data.TypeProviders` project. Note that you will need to make sure the files are deleted from the file system AND the project file
```
src/FSharp.Data.TypeProviders/TypeProviderEmit.fs
src/FSharp.Data.TypeProviders/TypeProviderEmit.fsi
```
4. run `.paket/paket.exe install` to add the appropriate project file entries to the project as specified in the `paket.references` file.
5. Make appropriate code changes to `TypeProviders.fs` to update to the new SDK API surface. This should be a relatively mechanical translation.  The majority of the code should remain the same, with a few simple translations:
    - Casing has changed for common constructor parameters: `IsErased => isErased`, `IsStatic => isStatic`, etc.
    - Some calls take an `Expr list` now instead of an `Expr []`, so you'll need to convert where appropriate with `List.ofArray` or `Array.toList`, etc.
6. Once the project builds again, run the tests by running `./build.sh` again. Some failures are to be expected. Once the test are running, you can investigate the results and we can go from there. The tests will likely fail after the transition, because there were some invariants that no longer hold. That's cool, we'll just work through them.

**Comment by gfritz** [comment]
I've forked this repo to start working on it. Thanks for the instructions!

**Comment by baronfel** [comment]
There was a bit of a question about how to handle the usage of `ProvidedTypeDefinition.CompileToGenerated` that no longer exists.  From what I can see, that method was used to hoist the types from one type definition into a target assembly, which should be doable by another, more standard mechanism now. I _believe_ that mechanism is now to create a `ProvidedAssembly` and use it as a parameter to all `ProvidedTypeDefintion`s created that need to be generated. IE moving universally from the `ProvidedTypeDefintion(className, baseType)` constructor to the `ProvidedTypeDefinition(assembly, namespace, className, baseType)` constructor.  Does this make sense to everyone? Paging @dsyme @sergey-tihon to sanity-check my logic here.

**Comment by sergey-tihon** [comment]
sorry, cannot find the use of `ProvidedTypeDefinition.CompileToGenerated`. could you please share the link?

**Comment by baronfel** [comment]
oh of course, sorry :D It's here https://github.com/fsprojects/FSharp.Data.TypeProviders/blob/master/src/FSharp.Data.TypeProviders/TypeProviders.fs#L390

**Comment by dsyme** [comment]
Yeah, I was wondering about this.  

I think you're right that emitting a generated ProvidedAssembly is correct.  The details may be subtle though, be careful :)

**Comment by sergey-tihon** [comment]
JFYI, [dev branch of SwaggerProvider](https://github.com/fsprojects/SwaggerProvider/tree/dev) is working sample of generating TP compiled using latest TPSDK. Take a look if you need the reference implementation.

Ping me anytime when you will have error in open PR, I'll try to help (at least with `simple` errors 😉  )

**Comment by gfritz** [comment]
Full disclosure - I am stuck 😃 .

I thought some combination of `hideObjectMembers=true/false` would make the 21 test failures pass, but it seems that is not working. Still grokking the SwaggerProvider too, but so far I cannot tell much.

Nothing worth opening a PR to this repo yet, but I could open one to my repo if that helps to see the changes so far.

~~https://github.com/gfritz/FSharp.Data.TypeProviders/pull/1~~

**Comment by sergey-tihon** [comment]
@gfritz could you please reopen PR to this repo?

this not only allows us to see changes, but
- we will see travis/appveyor execution results
- we will be able to commit to open PR

**Comment by gfritz** [comment]
To close the loop, there is this modern one by @thinkbeforecoding https://github.com/fsprojects/FSharp.Data.WsdlProvider that I have not finished testing for my scenario.

It should be good enough to close out this issue.

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/
