### ISSUE TITLE
Error in FSC: Could not find file '...\tmp8CF2.dll'

### ISSUE THREAD

**Issue by macfarmw** [fsprojects/FSharp.Data.TypeProviders#33]
### Description
Getting file not found error from FSC.exe when attempting to compile an F# console app that uses SqlDataConnection.

### Repro steps
1. Create new F# console app
2. Add NuGet reference to FSharp.Data.TypeProviders
3. Add reference to System.Data.Linq
4. Declare SqlDataConnection type in Program.cs using SqlDataConnection with a valid connection string
5. let db = connection.GetDataContext()

### Expected behavior
Program to compile with no errors.

### Actual behavior
Error FS0193 Could not find file 'C:\...\tmp8CF2.dll.
The exact tmp file name changes on each attempt to build.

### Known workarounds
None

### Related information 
* Windows 10
* .NET Framework 4.6.2

**Comment by dsyme** [comment]
This should be fixed with Visual Studio 15.7.2, please update and let us know

**Comment by macfarmw** [comment]
Yes, that fixed it.
