### ISSUE TITLE
Cannot build using dotnet build

### ISSUE THREAD

**Issue by halcwb** [fsprojects/FSharp.Data.TypeProviders#39]
### Description

When I try to build a project using FSharp.Data.TypeProviders, the project builds using VS 2019, but when trying dotnet build, i.e. msbuild command line the build fails.

I have created a repository to reproduce 

### Repro steps

Please provide the steps required to reproduce the problem

1. Clone the test project that demonstrates the problem: `git clone https://github.com/halcwb/DataPojectBuildProblem.git`

2. Open the solution using VS. There is an error because the connection string is empty. 

3. Try to build the solution using `dotnet build`

### Expected behavior

An error message indicating the empty connection string.

### Actual behavior

An error containing: 

> 
\DataContext.fs(18,15): error FS1108: The type 'String' is required here and is unavailable. You must add a reference to assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral

### Known workarounds

Using VS to build the solution.

### Related information 
.NET Core SDK (reflecting any global.json):
 Version:   3.1.201
 Commit:    b1768b4ae7

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.201\

Host (useful for support):
  Version: 3.1.3
  Commit:  4a9f85e9f8

.NET Core SDKs installed:
  2.1.701 [C:\Program Files\dotnet\sdk]
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.301 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  3.1.100 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]
  3.1.201 [C:\Program Files\dotnet\sdk]

**Comment by bbhoss** [comment]
Getting the same error, but I'm running .NET 5. It's too bad that such a major F# feature is completely broken for open source users.

**Comment by dsyme** [comment]
fixed in main

**Comment by dsyme** [comment]
> Getting the same error, but I'm running .NET 5. It's too bad that such a major F# feature is completely broken for open source users.

Note this is a very old collection of type providers that are Windows-specific.  For up-to-date type providers see https://fsharp.org/guides/data-access/
