### ISSUE TITLE
Doesn't seem to work with .NET Core

### ISSUE THREAD

**Issue by bbhoss** [fsprojects/FSharp.Data.TypeProviders#40]
### Description

I was following along on the official docs for [Query Expressions](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/query-expressions), until I hit a snag. It seems like this package just doesn't work at all on .NET 5 or .NET Core 3.1. I added the latest version via NuGet. Now I'm getting this message when compiling:
```
/Users/bbhoss/fse/src/foobar/foobar.fsproj : warning NU1701: Package 'FSharp.Data.TypeProviders 5.0.0.6' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
```
When I try to compile the example code I get an error:
```
/Users/bbhoss/fse/src/foobar/TodoItems/TodoItemsModel.fs(11,35): error FS1108: The type 'String' is required here and is unavailable. You must add a reference to assembly 'System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. [/Users/bbhoss/fse/src/foobar/foobar.fsproj]
```
Is there some way this can be fixed? This is one of the killer apps/fun demos of F#, and it flat out doesn't work.

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/
