### ISSUE TITLE
Will this project be maintained? Update to net5.0?

### ISSUE THREAD

**Issue by halcwb** [fsprojects/FSharp.Data.TypeProviders#42]
I would like to see that this project is updated to net5.0. Are there any plans to do this?

Specifically the MSSQL provider part. There is a SQLProvider project, but that also targets other Sql implementations and lacks the specific Sql support. This project does the job excellently, only it has not been updated for more than 2 years.

**Comment by dsyme** [comment]
This is a very tricky project to update, as it relies on .NET Framework code generators which I don't believe have been updated for a long time, and I don't think they are available in net5 installs

```
C:\GitHub\dsyme\fsharp>dir c:\Windows\Microsoft.NET\Framework\v4.0.30319\*.exe

 Directory of c:\Windows\Microsoft.NET\Framework\v4.0.30319

07/12/2019  09:10            46,832 cvtres.exe
07/12/2019  09:10            72,704 DataSvcUtil.exe
07/12/2019  09:10            97,776 EdmGen.exe
```

**Comment by dsyme** [comment]
In terms of type provider behaviour and specification, the project is excellent.

However the actual underlying technology is based on code generators from 2005-2008 era that just haven't stood the test of time.  So a re-implementation would really be needed, but that's a big job

**Comment by halcwb** [comment]
@dsyme Thanks for looking into this! I wonder if it would be feasible to take the approach as Linqpad does? Before I started using F#, I used C# and Linq. I wrote my queries in the excellent Linqpad tool from Joe Albahari. 

I just bought the version 6 of Linqpad. Now it seems that in Linqpad you can write regular F# Linq code using the net5.0. So, for example I can write:

```fsharp
query {
    for c in dc.Categories do
        select c
}
|> Seq.toList

```
with the net5.0 selected.

**Comment by colinbull** [comment]
@halcwb not really a conversation to have in this thread but what features are you specifically missing from the SqlProvider. As each provider is implemented independently it shouldn’t be too much of a problem to support specific things. Can I suggest you raise an issue in that project? If you copy me in I might be able to help?

**Comment by halcwb** [comment]
@colinbull I don't think I would miss that much features. But the old code is working excellent for me with the one restriction that I cannot upgrade it to the new net5.0. 

Another (maybe a misconception on my part) thing is that with the current lib I can specify in my connection that I only want tables nothing else:

```fsharp
    type schema = SqlDataConnection<ConnectionString = conString,
                                    LocalSchemaFile = @"./schema.dbml",
                                    Views = false,
                                    Functions = false,
                                    StoredProcedures = false,
                                    ContextTypeName = "PdmsDB">
```

I can also turn object tracking of:

`           ctx.DataContext.ObjectTrackingEnabled <- false`

I suspect this makes the code fast and I didn't see at first glance that this possible with SqlProvider. 

Besides, it's just a lot of code and there will be lots of little things you need to tweak to get things running again. But I am definitely going to look at SqlProvider.

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/

For WSDL see https://github.com/fsprojects/FSharp.Data.WsdlProvider for a more recent provider, also https://github.com/fsprojects/SwaggerProvider

**Comment by halcwb** [comment]
@dsyme Great list. Thanks. Maybe put this list in the readme of this repository?

P.S. I noticed that almost all of these libraries are still based on the old `Sytem.Data.SqlClient` instead of the new net5 compatible `Microsoft.Data.SqlClient`.

**Comment by dsyme** [comment]
I'll link it in the README, thanks

**Comment by dsyme** [comment]
> P.S. I noticed that almost all of these libraries are still based on the old Sytem.Data.SqlClient instead of the new net5 compatible Microsoft.Data.SqlClient.

Yes a round of updating really needs to happen now
