### ISSUE TITLE
Followup on https://github.com/dotnet/fsharp/issues/12078

### ISSUE THREAD

**Issue by Benjol** [fsprojects/FSharp.Data.TypeProviders#46]
@dsyme I don't know if you meant follow-up like this. If not sorry.

I've tried updating in the test project I described, and it doesn't appear to make any difference, unfortunately.

I'm going to investigate the newer versions, but there's quite a big solution behind this and I'm not sure all of it is going to play nicely with newer .NET versions.

Thanks.

**Comment by dsyme** [comment]
@Benjol I've reopened the issue, let's follow-up there
