### ISSUE TITLE
Can WSDL be a standalone package?

### ISSUE THREAD

**Issue by enricosada** [fsprojects/FSharp.Data.TypeProviders#6]
The others:
- EdmxFile, SqlDataConnection, SqlEntity: obsolete by community packages
- OData: ok, btw i see v2, latest is 4.0.
#### WSDL

WSDL it's good, it's used (but c# generated servicesclient are easier) because web services it's a technology used in real world (asmx/wcf/java interop).
It can improve a bit, if we find source code of svcutils (i should be somewhere oss i think) and remove dependency of svcutil.exe.

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/

For WSDL see https://github.com/fsprojects/FSharp.Data.WsdlProvider for a more recent provider, also https://github.com/fsprojects/SwaggerProvider
