### ISSUE TITLE
OData TP does not allow authorization headers?

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/FSharp.Data.TypeProviders#9]
This is a blocker for using private OData sources.

**Comment by dsyme** [comment]
Note this is a very old collection of type providers that are Windows-specific and .NET Framework-specific. For up-to-date type providers see https://fsharp.org/guides/data-access/

For WSDL see https://github.com/fsprojects/FSharp.Data.WsdlProvider for a more recent provider, also https://github.com/fsprojects/SwaggerProvider
